REQUIRED_SKILLS = [
      "Python",
    "Java",
    "JavaScript",
    "C++",
    "SQL",
    "HTML", 
    "CSS",
    "Django",
    "Flask",
    "React",
    "Angular",
    "Node.js",
    "AWS",
    "Azure",
    "Docker",
    "Kubernetes",
    "Git",
    "Machine Learning",
    "Data Analysis",
    "Natural Language Processing",
    "Deep Learning",
    "TensorFlow",
    "PyTorch",
    "Pandas",
    "NumPy",
    "Scikit-learn",
    "Tableau",
    "Power BI",
    "Agile Methodologies",
    "Scrum",
    "Project Management",
    "Communication Skills",
    "Problem-Solving",
    "Teamwork",
    "Leadership",
    "Time Management",
    "Critical Thinking",
    "Adaptability",
    "Creativity",
    "Attention to Detail",
    "Collaboration",
    "Conflict Resolution",
    "Emotional Intelligence",
    "Interpersonal Skills",
    "Public Speaking",
    "Writing Skills",
    "Analytical Skills",
    "Organizational Skills",
    "Customer Service",
    "Sales",
    "Marketing",
    "Financial Analysis",
    "Business Development",
    "Human Resources",
    "Legal Knowledge",
    "Foreign Languages",
    "REST APIs",
    "GraphQL",
    "Microservices",
    "Serverless Architecture",
    "CI/CD",
    "DevOps",
    "Cloud Computing",
    "Big Data",
    "Celery",
    "RabbitMQ",
    "Redis",
    "Elasticsearch",
    "AWS",
    "Azure",
    "Google Cloud",
    "POSTGRESQL",
    "MySQL",
    "MongoDB",
    "SQLite",
    "Linux",
    "Windows",  
    "macOS",
    "iOS",
    "Android",
]

class ResumeAnalyzer:
    @staticmethod
    def analyze(skills):
        missing_skills = []
        for skill in REQUIRED_SKILLS:
            if skill not in skills:
                missing_skills.append(skill)
        score = int((len(skills) / len(REQUIRED_SKILLS)) * 100)
        return {
            "score": score,
            "missing_skills": missing_skills
        }