# Generated by Django 6.0.6 on 2026-06-12 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0004_resume_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='companies',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='resume',
            name='education',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='resume',
            name='experience_years',
            field=models.IntegerField(default=0),
        ),
    ]
